[package]
name = "pubmatter"
version = "0.0.1"
entrypoint = "pubmatter.typ"
authors = ["rowanc1"]
license = "MIT"
description = "Parse and show publication frontmatter, including authors and affiliations"
repository = "https://github.com/curvenote/pubmatter"
keywords = ["frontmatter", "authors", "affiliations", "abstract", "orcid"]
